### ISSUE TITLE
说5G设备问题，麻烦把事情说清楚

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [gfw-breaker/banned-news#1]
https://github.com/gfw-breaker/banned-news/blob/master/pages/nsc413/n11294608.md?t=06021236

记者解释链接：
https://www.bilibili.com/video/av54122944/?spm_id_from=333.334.b_72616e6b696e675f746563686e6f6c6f6779.5

**Comment by Yannnnnnnnnnnn** [comment]
讨厌在一个讨论技术的地方讨论政治！

**Comment by gfw-breaker** [comment]
@Yannnnnnnnnnnn 何必费力把视频搬到B站上，把GFW打开，直接让网民看到更多的报道不更好吗？
这不是讨论政治，我只是像分享视频一样的网友一样，把墙外的资源搬到墙内而已。
