### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by begood0513** [gfw-breaker/banned-news#2]
我们很多人一起在做QQ项目，群发视频，但是现在封号很严重，所以想在Git上做一个新闻网，在search的时候看到您的项目，很感兴趣，看到还可以搭建代理播视频，请问这个播视频的VPS会被封吗？一个VPS可以支撑多少人同时观看视频？可不可以只代理youtube上指定栏目的视频（比如江峰、文昭等等）？
急盼答复，谢谢！

**Comment by begood0513** [comment]
另外，我们可能想自己组织一些内容，不知道怎么把网页的内容，转化为Github上的Markdown文件，比如我们想把“动态网”首页转到Github上，这个怎么做？

**Comment by gfw-breaker** [comment]
@begood0513  YouTube代理那个方案弃用了，因为太容易太封锁了。关于如何把网页同步到GitHub上，可以参数这里的[脚本](https://github.com/gfw-breaker/banned-news/tree/master/scripts)。
如果是要让网民不翻墙就能看YouTube视频的话，我推荐使用[网门安卓版](https://github.com/oGate2/oGate)，它后台会动态创建服务器，所以不能完全封锁掉。
如果是要让网民不翻墙就能看新闻的话，我推荐使用我这个项目，不需要装任何软件，在所有平台都能访问，而且便于分享。

**Comment by begood0513** [comment]
主要是您的项目内容的问题，我们想自己选一些内容。
网门在国内能安装吗？

**Comment by gfw-breaker** [comment]
@begood0513 网门就是为国内网民开发，可以安装。 留个邮箱细说吧。

**Comment by begood0513** [comment]
begood0513@gmail.com
